//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdminTbl
{
    public int adminId { get; set; }
    public string adminName { get; set; }
    public string password { get; set; }
}

public partial class TblAppointment
{
    public int appointmentId { get; set; }
    public string personName { get; set; }
    public string subject { get; set; }
    public decimal phone { get; set; }
    public string description { get; set; }
    public System.DateTime date { get; set; }
}

public partial class TblContact
{
    public string name { get; set; }
    public decimal phone { get; set; }
    public string subject { get; set; }
    public string message { get; set; }
}

public partial class TblUser
{
    public string personName { get; set; }
    public string userName { get; set; }
    public string age { get; set; }
    public decimal phone { get; set; }
    public string password { get; set; }
    public string description { get; set; }
}
