//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMEETUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public string personName { get; set; }
        public string userName { get; set; }
        public string age { get; set; }
        public decimal phone { get; set; }
        public string password { get; set; }
        public string description { get; set; }
    }
}
